### ISSUE TITLE
遵守 Google Fonts 上游仓库结构

### ISSUE THREAD

**Issue by Yuiinars** [lxgw/LxgwWenKai-Lite#3]
您做的字体十分美观，但是想用在网站上却比较困难，比如我更喜欢Google Fonts，它可以使字体更方便地安装在网站上，还请您能遵守 Google Fonts 上游仓库结构： https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure
祝谢！

**Comment by lxgw** [comment]
花了一个多小时生成 ufo 并转移提交，看看怎么样 ![](https://face.t.sinajs.cn/t4/appstyle/expression/ext/normal/7b/2018new_miaomiao_org.png)
