### ISSUE TITLE
关于为等宽版本增加ExBold字重的请求 / Request on adding an ExBold version of LXGWWenKaiMono-Lite

### ISSUE THREAD

**Issue by cxw620** [lxgw/LxgwWenKai-Lite#5]
参考此PR comment的信息.
See this PR comment for information.
https://github.com/GyulyVGC/sniffnet/pull/89#issuecomment-1447278008

请求为霞鹜文楷等宽版本增加ExBold字重版本解决[这个现象](https://stackoverflow.com/questions/14477265/css-white-text-on-black-background-looks-bolder)的问题, 或者想请教一下是否有什么可能的解决方案? 
Would you please add an ExBold version of `LxgwWenKaiMono`? Or could you share me any possible solution on the effect GyulyVGC mentioned?

**Comment by lxgw** [comment]
抱歉，没有这个计划，请您选用其他字体。

**Comment by lxgw** [comment]
非常抱歉，限于字体本身风格及本人技术水平，目前没有添加更粗字重的计划，请您选用其他字体，敬请谅解！
