### ISSUE TITLE
感谢作者！请问这个字体有英文版吗？

### ISSUE THREAD

**Issue by eihrceon35104** [lxgw/LxgwWenKai-Lite#6]

**Comment by lxgw** [comment]
您可以直接用这个字体的西文部分，或者自行 fork 一个删去中日韩字符的「英文版」。

**Comment by luckykellan** [comment]
> 您可以直接用这个字体的西文部分，或者自行 fork 一个删去中日韩字符的「英文版」。

请问作者怎么删除其他语言部分？业务需要只想保留韩文

**Comment by lxgw** [comment]
> > 您可以直接用这个字体的西文部分，或者自行 fork 一个删去中日韩字符的「英文版」。
> 
> 请问作者怎么删除其他语言部分？业务需要只想保留韩文

https://github.com/lxgw/LxgwWenKai/tree/main/documentation/Hangul 这里有单独的韩文版，虽然可能有错字。
